// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const backgroundColor: string
export const scrolledHeaderBackgroundColor: string
export const midpointColor1: string
export const midpointColor2: string
export const headerHeightMobile: string
export const headerHeightDesktop: string
export const animationLengthLonger: string
export const NavigationItem: string
export const Button: string
export const Button_Sidebar: string
export const Button_NoStyle: string
export const Active: string
