// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const backgroundColor: string
export const scrolledHeaderBackgroundColor: string
export const midpointColor1: string
export const midpointColor2: string
export const headerHeightMobile: string
export const headerHeightDesktop: string
export const animationLengthLonger: string
export const SingleProject: string
export const ProjectName: string
export const Image: string
export const Img: string
export const Information: string
export const ShortDescription: string
export const TechnologiesUsed: string
