// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const backgroundColor: string
export const scrolledHeaderBackgroundColor: string
export const midpointColor1: string
export const midpointColor2: string
export const headerHeightMobile: string
export const headerHeightDesktop: string
export const animationLengthLonger: string
export const PageHeader: string
export const PageHeader_AfterScroll: string
export const PageHeader_AfterScroll_WithSidebar: string
export const Name: string
export const Navigation: string
export const Burger: string
