// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const backgroundColor: string
export const scrolledHeaderBackgroundColor: string
export const midpointColor1: string
export const midpointColor2: string
export const headerHeightMobile: string
export const headerHeightDesktop: string
export const animationLengthLonger: string
export const Sidebar: string
export const Link: string
export const Open: string
export const Close: string
export const Scrolled: string
