// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const backgroundColor: string
export const scrolledHeaderBackgroundColor: string
export const midpointColor1: string
export const midpointColor2: string
export const headerHeightMobile: string
export const headerHeightDesktop: string
export const animationLengthLonger: string
export const AboutMe: string
export const Header: string
export const HeaderMotto: string
export const Content: string
export const Description: string
export const Technologies: string
export const ImageDiv: string
